default:
  autoload:
    '': %paths.base%/behat-tests/bootstrap
  suites:
    default:
      paths:
        - %paths.base%/behat-tests
      contexts:
        - DefaultFeatureContext
        - TeamDeeson\Behat\Context\AdminContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    Behat\MinkExtension:
      goutte: ~
      selenium2: ~
      base_url: http://localhost/
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drupal'
      drupal:
        drupal_root: '%paths.base%/docroot'
      drush:
        alias: 'docker'
      selectors:
        message_selector: '.message'
        error_message_selector: '.error'
        success_message_selector: '.success'
        warning_message_selector: '.warning'
      region_map:
        comments: '.comments'
        header: '#header'
        'blog listing': '.node--view-mode-blog-listing'
        pager: '.pagination-nav'

pipelines:
  extensions:
    Bex\Behat\ScreenshotExtension:
      active_image_drivers: unsee
      image_drivers:
        unsee:
          expire: '1h' # possible values: '10m', '30m', '1h'
    Behat\MinkExtension:
      base_url: http://localhost:8080/
    Drupal\DrupalExtension:
      drush:
        alias: 'pipelines'
        binary: %paths.base%/vendor/bin/drush
