version: "3"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.3.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
#      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
      - ./.persist/mysql:/var/lib/mysql # I want to manage volumes manually.
    networks:
      - isolated

  php:
# 2. Images without Drupal – wodby/drupal-php:[PHP_VERSION]-[STABILITY_TAG].
    image: wodby/drupal-php:7.1-2.4.3
#    image: wodby/drupal-php:7.0-2.1.0
#    image: wodby/drupal-php:5.6-2.1.0
#    image: wodby/drupal-php:5.3-2.1.0
    environment:
      PHP_FPM_CLEAR_ENV: "false"
      DOCKER_LOCAL: 1
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
      PHP_IDE_CONFIG: "serverName=localhost"       # Needed for xdebug for drush commands.
    volumes:
      - ./:/var/www/html:cached
      - ./.persist/public:/var/www/html/docroot/sites/default/files
      - ./.persist/private:/private
    networks:
      - isolated

  nginx:
# wodby/drupal-nginx:[DRUPAL_VERSION]-[NGINX_VERSION]-[STABILITY_TAG].
    image: wodby/drupal-nginx:8-1.13-2.4.2
#    image: wodby/drupal-nginx:7-1.10-2.1.0
#    image: wodby/drupal-nginx:6-1.10-2.1.0
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/docroot
    volumes:
      - ./:/var/www/html:cached
      - ./.persist/public:/var/www/html/docroot/sites/default/files
    labels:
      - 'traefik.port=80'
      - "traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}.localhost"
    networks:
      - isolated
      - proxy

  redis:
    image: wodby/redis:3.2-2.1.0
    networks:
      - isolated

  solr:
## wodby/drupal-solr:[DRUPAL_VERSION]-[SOLR_VERSION]-[STABILITY_TAG].
    image: wodby/drupal-solr:8-6.4-2.0.0
##    image: wodby/drupal-solr:8-6.3-2.0.0
##    image: wodby/drupal-solr:8-5.5-2.0.0
##    image: wodby/drupal-solr:7-6.4-2.0.0
##    image: wodby/drupal-solr:7-6.3-2.0.0
##    image: wodby/drupal-solr:7-5.5-2.0.0
    environment:
      SOLR_HEAP: 1024m
    labels:
      - 'traefik.port=8983'
      - "traefik.frontend.rule=Host:solr.${COMPOSE_PROJECT_NAME}.localhost"
    networks:
      - isolated
      - proxy

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.port=8025'
      - "traefik.frontend.rule=Host:mailhog.${COMPOSE_PROJECT_NAME}.localhost"
    networks:
      - isolated
      - proxy

networks:
  proxy:
    external: true
  isolated:
    external: false
